language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - ruby-2.7.0-preview2
  - jruby-19mode
  - truffleruby-head

notifications:
  email:
    on_success: never
    recipients:
      - badboy@archlinux.us

