name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        ruby: [2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.9, jruby]
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake
